---
abstract: 'A minting profile for Modules written with MooseX::Declare'
author:
  - 'Daniel B <dbr@cpan.org>'
build_requires:
  Carp: 0
  ExtUtils::MakeMaker: 0
  File::Spec::Functions: 0
  List::Util: 0
  Module::Build: 0.3601
  Scalar::Util: 0
  Test::CheckDeps: 0.006
  Test::More: 0.94
  Test::UseAllModules: 0
  perl: 5.004
  strict: 0
  warnings: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
  Module::Build: 0.3601
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300039, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Dist-Zilla-MintingProfile-MooseXDeclare
provides: {}
requires:
  Dist::Zilla::Role::MintingProfile::ShareDir: 0
  Moose: 0
  namespace::autoclean: 0
resources:
  homepage: https://github.com/xdbr/Dist-Zilla-MintingProfile-MooseXDeclare
  repository: https://github.com/xdbr/Dist-Zilla-MintingProfile-MooseXDeclare.git
version: 0.400
x_authority: cpan:DBR
